---
detectors:
  IrresponsibleModule:
    enabled: false
  UncommunicativeModuleName:
    accept:
      - 'V1'

directories:
  "app/controllers":
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  "app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/mailers":
    InstanceVariableAssumption:
      enabled: false
  "app/models":
    InstanceVariableAssumption:
      enabled: false

exclude_paths:
  - 'bin/**/*'
  - 'db/**/*'
  - 'config/**/*'
  - 'vendor/**/*'
  - Rakefile
  - config.ru
