#!/bin/sh

# Script for performing all operations related to hardening the AutoGrid Ubuntu image

# trace on
set -x
# break on error
set -e
# Delete package cache
rm -rf /var/cache/apt/*

# Remove unnecessary user accounts.
sed -i -r '/^(autogrid|root|_apt)/!d' /etc/group
sed -i -r '/^(autogrid|root|_apt)/!d' /etc/passwd
sed -i -r '/^(autogrid|root|_apt)/!d' /etc/shadow

# Remove interactive login shell for everybody but autogrid.
sed -i -r '/^autogrid:/! s#^(.*):[^:]*$#\1:/sbin/nologin#' /etc/passwd

sysdirs="
  /bin
  /etc
  /lib
  /sbin
  /usr
"

# Removing files generated by sed commands above (group-, passwd- and shadow-)
find $sysdirs -xdev -type f -regex '.*-$' -exec rm -f {} +

# Ensure system dirs are owned by root and not writable by anybody else.
find $sysdirs -xdev -type d \
  -exec chown root:root {} \; \
  -exec chmod 0755 {} \;

# Remove existing crontabs, if any.
rm -fr /var/spool/cron
rm -fr /etc/crontabs
rm -fr /etc/periodic

# Remove init scripts since we do not use them.
rm -fr /etc/init.d
rm -fr /lib/rc
rm -fr /etc/conf.d
rm -fr /etc/inittab
rm -fr /etc/runlevels
rm -fr /etc/rc.conf

# Remove kernel tunables since we do not need them.
rm -fr /etc/sysctl*
rm -fr /etc/modprobe.d
rm -fr /etc/modules

# Remove fstab since we do not need them.
rm -f /etc/fstab

# Remove all but a handful of admin commands.
# find /sbin /usr/sbin ! -type d \
#  -a ! -name nologin \
#  -delete

# Remove all but a handful of executable commands.
# find /bin /usr/bin ! -type d \
#  -a ! -name cd \
#  -a ! -name ls \
#  -a ! -name sh \
#  -a ! -name bash \
#  -a ! -name dir \
#  -a ! -name rm \
#  -a ! -name find \
#  -a ! -name test \
#  -delete

# Remove broken symlinks (because we removed the targets above).
find $sysdirs -xdev -type l -exec test ! -e {} \; -delete


